name: getx_mvc_templet
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rename: ^2.0.1
  url_launcher: ^6.1.7
  shimmer: ^2.0.0
  flutter_local_notifications: ^12.0.4
  firebase_messaging: ^14.0.3
  flutter_screenutil: ^5.5.3+2
  shared_preferences: ^2.0.15
  connectivity: ^3.0.6
  intl: ^0.17.0
  get: ^4.6.5
  flutter_native_splash: ^2.2.9
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.68.0
  table_calendar: ^3.0.8
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0





flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Urbanist
     fonts:
       - asset: assets/fonts/Urbanist/Urbanist-Regular.ttf


  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
